### ISSUE TITLE
Enable reuse of SimpleITK "core" with python builds.

### ISSUE THREAD

**Issue by blowekamp** [jcfr/SimpleITKPythonPackage#1]
The directories under in "SimpleITK/Wrapping/" such as "SimpleITK/Wrapping/Python" can be configured as an entirely separate project which just uses an installed version of the SimpleITK core libraries. This is useful when compiling multiple SimpleITK packages because it enables the reuse of a single SimpleITK library compilation.

I recommend adding a separate ExternalProject for this python wrapping directory. Additionally, there should be a configuration options to specify an SimpleITK_DIR and the required SWIG executable ( the transitive ITK_DIR should happen magically?). This option should bypass the SimpleITK core library compilation.

The goal of this is to create a script to build for multiple versions of python quickly.

**Comment by jcfr** [comment]
See https://github.com/jcfr/SimpleITKPythonPackage/compare/1-enable-reuse-of-simpleitk-core-libraries

Next step will be to teach `scikit-build` to check for additional option.

```
1) Get SimpleITKPythonPackage source

2) Build SimpleITKPythonPackage with SimpleITKPythonPackage_BUILD_PYTHON set to OFF

3) TODO: Mechanism to set SimpleITK_DIR and SWIG_EXECUTABLE  through scikit-build ... 

4) Build "flavor" of package using `python setup.py bdist_wheel`
```

**Comment by jcfr** [comment]
Fixed in https://github.com/jcfr/SimpleITKPythonPackage/commit/119ad2326b91a95a3fc871cb3157cd6abe71174a
