### ISSUE TITLE
numpy is not a build or install requirement 

### ISSUE THREAD

**Issue by blowekamp** [jcfr/SimpleITKPythonPackage#2]
The numpy python library is currently not a build requirement. SimpleITK compiled fine with out it. There is just a failing test, and warning during setting up the testing virtual environment. Currently numpy is optional for installation. Only the GetArrayFromImage and GetImageFromArray methods will through an exception.

**Comment by jcfr** [comment]
> The numpy python library is currently not a build requirement. SimpleITK compiled fine with out i

Good catch, I will remove it.
